language: python
python:
- '3.6'
- 3.7-dev
- nightly
install:
- pip install -e .[test]
- pip install codecov
script:
- python setup.py test
- codecov
deploy:
  provider: pypi
  user: rchatterton
  password:
    secure: ikMMpx+VkzORs+2Tt1vip9askxBHeI8Cw1dL2qGAKU90DvaB1Oa9ssInPwDElvDhMdjZ4x37aXbd/p16yFYoOdgVAOl6FoH5RK2q2HCOfCLzpNxZRWursRNQTb3v+pMTgntcPo3RaQ9aJImNaqKVm5qn67aaKhbyvGLQt4Yci323AujtIdnwav6GdEmi8k6qLA4bU2NOPVFgQooYOaFKoJfvJUDRMA20vMCzLXfXTpzqJ9fqgJAoJUC+CKjTJVtbVlbnmeZG24maqMg1Sct5F28j8yro8B5mgZoYAZ+HzpAywZvV1Mf1+tlnMtfKkBGVOrZ7RnPLYo1s0Nw4GR3MZYAcl1oPUxxxeGkO59uqkkRK+oTtCOfblNm304anAf41vsV1OelXnOIp9YrtVTfrkYK5CmZsRyTP9iVfluS0rCxSXF9Pp2mmLDpmwtHEA0eDSj4w42FVsS0M+hhkzsEK60hoJvFLmIe7CA2neWvg65Tkxe2CFaGsh15QEqsu6zDHiu63zvboaZZIK4a1r7+qC7Hf4IartzwlGCqNlncRlA3aXpdXmq0Jwj2wSrhkvJdH3r+X5lxw3HeI8mCb+40qyCsfayqPBc0n7PCpC71D+YRVGGxL9E2errkBkNx1ylCWIVbogP45rDv8QcvlR6WTgTlcvPEYV6oqnucVE2oDnf4=
  on:
    tags: true
    branch: master
  distributions: sdist bdist_wheel
